services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: unless-stopped
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    ports:
      - "${DB_PORT}:3306"

  db_test:
    image: mysql:latest
    container_name: mysql_db_test
    restart: unless-stopped
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mywallet_test
    ports:
      - "3310:3306"